# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('updateTime', models.DateTimeField(default=timezone.now())),
                ('readCount', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=1)),
            ],
        ),
    ]
